export const keywords = [
  'Desarrollo Web',
  'Frontend Development',
  'HTML5',
  'CSS3',
  'JavaScript',
  'TypeScript',
  'React JS',
  'Next JS',
  'Tailwind CSS',
  'Git',
  'GitHub',
  'Figma',
  'Sass',
  'Firebase',
  'Platzi',
  'Adobe XD',
  'Scrum',
  'Extreme Programming',
  'English Proficiency',
  'Responsive Web Design',
  'UI/UX Design',
  'Mobile-first Approach',
  'Cross-browser Compatibility',
  'Performance Optimization',
  'Web Developer Portfolio',
  'Software Engineer',
  'Frontend Engineer',
  'Creative Web Solutions',
  'User-Centric Development',
  'Agile Methodologies',
  'Web Development Projects',
  'Web Design Prototyping',
  'Internationalization (i18n)',
];
