import type { Metadata } from 'next';
import { Onest } from 'next/font/google';
import { Header } from '@/app/ui/components/shared/Header';
import './styles/globals.css';

const onest = Onest({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={onest.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
